### ISSUE TITLE
shellcheck

### ISSUE THREAD

**Issue by AladW** [geyslan/xrasengan#2]
I'd suggest to run xrasengan script through shellcheck, to find quoting errors amongst others:

http://www.shellcheck.net/

**Comment by geyslan** [comment]
@AladW, thank you for that tip. However I think this project is dead. It could be so much simpler just to wrap the original `xrandr command input` and and force it using the workaround part [https://github.com/geyslan/xrasengan/blob/master/xrasengan#L145-L153](https://github.com/geyslan/xrasengan/blob/master/xrasengan#L145-L153)

What do you think? Be free to change it as you like.

**Comment by geyslan** [comment]
@AladW, [done](https://github.com/geyslan/xrasengan/commit/3c3bb5ce660d8f4a659d8b4ed2138b40539473a7).

Tks.
